version: "3"
services:
  #WEBSERVICE#
  #web-service:
  #  build:
  #    context: ./nginx
  #    dockerfile: Dockerfile
  #  image: aschenputtel.abinsall.com.nginx:latest
  #  restart: always
  #  depends_on:
  #    - app-service
  #ports:
  #  - 8000:80
  #  networks:
  #    - aschenputtel.abinsall.com
  #  volumes:
  #    - ./www:/www:ro
  #    - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
  #  env_file:
  #    - ./.env_data/.dev.nginx.env
  #DJANGO + GUNICORN#
  app-service:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: aschenputtel.abinsall.com.app:latest
    restart: always
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8001 -t 3600 --workers=6
    ports:
      - 8000:8001
    networks:
      - aschenputtel.abinsall.com
    volumes:
      - models-volume-aschenputtel:/home/app/web/cache:rw
    env_file:
      - ./.env_data/.dev.app.env

networks:
  aschenputtel.abinsall.com:

volumes:
  models-volume-aschenputtel:
